/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUtmRouteImport } from './routes/_authenticated/utm'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversionsRouteImport } from './routes/_authenticated/conversions'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify-webhook'
import { Route as AuthenticatedHelpApiKeyRouteImport } from './routes/_authenticated/help.api-key'
import { Route as ApiPublicShopifyOauthCallbackRouteImport } from './routes/api/public/shopify-oauth.callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUtmRoute = AuthenticatedUtmRouteImport.update({
  id: '/utm',
  path: '/utm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversionsRoute =
  AuthenticatedConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHelpApiKeyRoute = AuthenticatedHelpApiKeyRouteImport.update({
  id: '/help/api-key',
  path: '/help/api-key',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicShopifyOauthCallbackRoute =
  ApiPublicShopifyOauthCallbackRouteImport.update({
    id: '/api/public/shopify-oauth/callback',
    path: '/api/public/shopify-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversions': typeof AuthenticatedConversionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/utm': typeof AuthenticatedUtmRoute
  '/help/api-key': typeof AuthenticatedHelpApiKeyRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/shopify-oauth/callback': typeof ApiPublicShopifyOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conversions': typeof AuthenticatedConversionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/utm': typeof AuthenticatedUtmRoute
  '/help/api-key': typeof AuthenticatedHelpApiKeyRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/shopify-oauth/callback': typeof ApiPublicShopifyOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conversions': typeof AuthenticatedConversionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/utm': typeof AuthenticatedUtmRoute
  '/_authenticated/help/api-key': typeof AuthenticatedHelpApiKeyRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
  '/api/public/shopify-oauth/callback': typeof ApiPublicShopifyOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conversions'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/utm'
    | '/help/api-key'
    | '/api/public/shopify-webhook'
    | '/api/public/shopify-oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conversions'
    | '/dashboard'
    | '/onboarding'
    | '/settings'
    | '/utm'
    | '/help/api-key'
    | '/api/public/shopify-webhook'
    | '/api/public/shopify-oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conversions'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/utm'
    | '/_authenticated/help/api-key'
    | '/api/public/shopify-webhook'
    | '/api/public/shopify-oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
  ApiPublicShopifyOauthCallbackRoute: typeof ApiPublicShopifyOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/utm': {
      id: '/_authenticated/utm'
      path: '/utm'
      fullPath: '/utm'
      preLoaderRoute: typeof AuthenticatedUtmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversions': {
      id: '/_authenticated/conversions'
      path: '/conversions'
      fullPath: '/conversions'
      preLoaderRoute: typeof AuthenticatedConversionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/shopify-webhook': {
      id: '/api/public/shopify-webhook'
      path: '/api/public/shopify-webhook'
      fullPath: '/api/public/shopify-webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/help/api-key': {
      id: '/_authenticated/help/api-key'
      path: '/help/api-key'
      fullPath: '/help/api-key'
      preLoaderRoute: typeof AuthenticatedHelpApiKeyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/shopify-oauth/callback': {
      id: '/api/public/shopify-oauth/callback'
      path: '/api/public/shopify-oauth/callback'
      fullPath: '/api/public/shopify-oauth/callback'
      preLoaderRoute: typeof ApiPublicShopifyOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConversionsRoute: typeof AuthenticatedConversionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUtmRoute: typeof AuthenticatedUtmRoute
  AuthenticatedHelpApiKeyRoute: typeof AuthenticatedHelpApiKeyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConversionsRoute: AuthenticatedConversionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUtmRoute: AuthenticatedUtmRoute,
  AuthenticatedHelpApiKeyRoute: AuthenticatedHelpApiKeyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
  ApiPublicShopifyOauthCallbackRoute: ApiPublicShopifyOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
